WeatherApplication/Controllers/AllWeatherDetailsController.cs
using Microsoft.AspNetCore.Mvc;


namespace WeatherApplication.Controllers
{
    [Controller]
    public class AllWeatherDetailsController : Controller
    {
        [Route("/")]
        public IActionResult ReturnAllWeatherDetails()
        {
			return View();
		}
    }
}

WeatherApplication/Controllers/CityWeatherDetailsController.cs
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Services;

namespace WeatherApplication.Controllers
{
    [Controller]
    public class CityWeatherDetailsController : Controller
    {
        private readonly ISetViewBag _setViewBag;

		public CityWeatherDetailsController(ISetViewBag setViewBag) 
        {
			_setViewBag = setViewBag;
		}
        [Route("/weather/{cityCode}")]
        public IActionResult ReturnCityWeatherDetails(string? cityCode)
        {
            ViewBag.Title = _setViewBag;
			return View(null,cityCode);
        }

    }
}

WeatherApplication/ViewComponents/AllBoxesViewComponent.cs
using Interfaces;
using Microsoft.AspNetCore.Mvc;
using Services;
namespace WeatherApplication.ViewComponents
{
    [ViewComponent]
    public class AllBoxesViewComponent: ViewComponent
    {
        private readonly ICitiesProvider _citiesProvider;

		public AllBoxesViewComponent(ICitiesProvider citiesProvider)
        {
			_citiesProvider = citiesProvider;

		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			

			return  View("AllBoxesPartialView", _citiesProvider.CreatList());
		}
    }
}

WeatherApplication/ViewComponents/BoxCityWeatherDetailsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Interfaces;

namespace WeatherApplication.ViewComponents
{
	public class BoxCityWeatherDetailsViewComponent : ViewComponent
	{
		private readonly ICitiesProvider _citiesProvider;

		public BoxCityWeatherDetailsViewComponent(ICitiesProvider citiesProvider)
		{
			_citiesProvider = citiesProvider;

		}

		private string ReturnBoxColor(int? temperature)
		{
			return temperature switch
			{
				(< 44) => "box-blue",
				(>= 44) and (< 74) => "box-green",
				(>= 74) => "box-orange",
				(null) => "box-blue"
			};
		}
		public async Task<IViewComponentResult> InvokeAsync(string? cityCode)
		{
			List<CityWeather> cityWeatherList = _citiesProvider.CreatList();

			CityWeather? cityWeather = cityWeatherList.SingleOrDefault(cw => cw.CityUniqueCode == cityCode);

			if (cityWeather == null)
			{
				return View("ErrorPage");
			}

			ViewBag.CssClass = ReturnBoxColor(cityWeather.TemperatureFahrenheit);

			return View("CityWeatherDetailsBoxDesign", cityWeather);
		}
	}
}

WeatherApplication/ViewComponents/BoxViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Models;

namespace WeatherApplication.ViewComponents
{
	public class BoxViewComponent : ViewComponent
	{

		private string ReturnBoxColor(int? temperature)
		{
			return temperature switch
			{
				(< 44) => "box-blue",
				(>= 44) and (< 74) => "box-green",
				(>= 74) => "box-orange",
				(null) => "box-blue"
			};
		}
		public async Task<IViewComponentResult> InvokeAsync(CityWeather cityWeather)
		{
			ViewBag.CssClass = ReturnBoxColor(cityWeather.TemperatureFahrenheit);
			return View("DefaultBoxDesign", cityWeather);	
		}
	}
}

WeatherApplication/Views/AllWeatherDetails/ReturnAllWeatherDetails.cshtml
@{
	ViewBag.Title = "Weather";
}
@await Component.InvokeAsync("AllBoxes")

WeatherApplication/Views/CityWeatherDetails/ReturnCityWeatherDetails.cshtml
@model string

<div class="margin-auto">
	@await Component.InvokeAsync("BoxCityWeatherDetails", Model)
	<a class="margin-set" href="/">Back to Home Page</a>
</div>

WeatherApplication/Views/Shared/Components/AllBoxes/AllBoxesPartialView.cshtml
@model IEnumerable<CityWeather>

<div class="flex-borderless margin-auto container">
	@foreach (CityWeather cityWeather in Model)
	{
		@await Component.InvokeAsync("Box",cityWeather)
	}
</div>

WeatherApplication/Views/Shared/Components/Box/DefaultBoxDesign.cshtml
@model CityWeather

<div class="@ViewBag.CssClass flex-borderless">		
	<div class="left-items">
		<div class="font-size bold-text">@Model.CityName</div>
		<div class="text-dark-grey bold-text">@Model.DateAndTime.ToString("hh:mm tt")</div>
		<a href="/weather/@Model.CityUniqueCode">Details</a>
	</div>
	<div class="vertical-line"></div>
	<div class="fahrenheit-font-size bold-text">@Model.TemperatureFahrenheit</div>
	<div class="degree-symbol-style text-grey">°F</div>
</div>

WeatherApplication/Views/Shared/Components/BoxCityWeatherDetails/CityWeatherDetailsBoxDesign.cshtml
@model CityWeather

<div class=@ViewBag.CssClass>		
	<div class="flex-borderless">
		<div  class="left-items">
			<div class="font-size bold-text">@Model.CityName</div>
			<div class="text-grey bold-text">@Model.DateAndTime.ToString("dd MMM yyy")</div>
			<div class="text-grey bold-text">@Model.DateAndTime.ToString("hh:mm tt")</div>
		</div>
		<div class="vertical-line"></div>
		<div class="fahrenheit-font-size bold-text">@Model.TemperatureFahrenheit</div>
		<div class="degree-symbol-style text-grey">°F</div>
	</div>
</div>

WeatherApplication/Views/Shared/Components/BoxCityWeatherDetails/ErrorPage.cshtml
<div>
	<h1>Error city not found</h1>
	<script>alert("No City Found");</script>
</div>

WeatherApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="/StyleSheet.css" />
    <meta charset="utf-8" />
</head>
<body>
    <h1 class="header">Weather</h1>
    <div>
        @RenderBody()
    </div>
</body>
</html>